### ISSUE TITLE
jabcodeReader cannot decode if image size too large

### ISSUE THREAD

**Issue by jackschmidt** [jabcode/jabcode#16]
Perhaps this is a documentation issue, but larger ("higher quality") images cannot be read by jabcodeReader. I think the limit is around 1024 pixels. The default for phone cameras is much higher than this, so my initial tests all resulted in failure. Generally in a web-app like jabcode.org one sets the resolution to something more reasonable. For the command line tool it might warn if an image is much larger than expected.

I used jabcodeWriter to make a png, displayed the png, took a photo, and used jabcodeReader to decode the result, but got:
```
JABCode Error: Too few finder patterns found
JABCode Error: Decoding jabcode failed
```

### Working: (992x1037)

![992x1037](https://user-images.githubusercontent.com/1107865/50370289-13e9a280-0572-11e9-9e08-895b0d84f5a0.png)

### Error message: (1006x1052)

![1006x1052](https://user-images.githubusercontent.com/1107865/50370290-1cda7400-0572-11e9-9c04-e939b0af5aef.png)

**Comment by jabcode** [comment]
Thanks for your feedback. This is a known problem. The code reader shall resize the image before sending it to the decoder. But this is done blindly without knowing the module size. In the new version, the detected module size will be returned from the detector, so that the code reader can adjust the image resolution accordingly.
