### ISSUE TITLE
Suggestion for site

### ISSUE THREAD

**Issue by TheRedSpy15** [jabcode/jabcode#25]
The jabcode creator on the site I think should display the maximum amount of data that can be entered in the message box with the given configuration

**Comment by goblin** [comment]
Similarly, a command-line tool would be useful that could output the maximum input size for a given configuration.

Also, ideally, the remaining space should be used for parity data, making error correction more likely, rather than just being padded with dummy bits...

**Comment by goblin** [comment]
In the meantime, I've used binary search to figure out the minimum message size at which the encoder refuses to encode it (or decoder fails to properly decode it). I've done this for all ECC levels (plus the "0" ECC level which I hacked in `encoder.h` to have wc = 3 and wr = 9 -- for some reason currently the "0" level is defined the same as level "3", contrary to Table 18 on page 41 of the paper).

Then I added two extra ECC levels (only checked this for 8 colours), -1 with wc = 3 and wr = 10; and -2 with wc = 3 and wr = 11 -- both of which still decoded fine. Having wr of 12 or more results in LDPC decoding failures, possibly due to the fact there's not enough bits to encode them in the metadata. Why are ECC choices limited so much..?

colours | ECC level | size
-------- | ----------- | ---
4 | 0 | 3394
4 | 1 | 3182
4 | 2 | 2909
4 | 3 | 2828
4 | 4 | 2545
4 | 5 | 2181
4 | 6 | 1696
4 | 7 | 1271
4 | 8 | 1016
4 | 9 | 846
4 | 10 | 725
8 | -2 | 5554
8 | -1 | 5346
8 | 0 | 5091
8 | 1 | 4773
8 | 2 | 4363
8 | 3 | 4246
8 | 4 | 3817
8 | 5 | 3272
8 | 6 | 2544
8 | 7 | 1907
8 | 8 | 1525
8 | 9 | 1270
8 | 10 | 1089

Note that these results are not consistent with Table 1 on page 13 of the paper! This table mentions wc = 4, wr = 7, which corresponds to ECC level 5. For 4 colors, the maximum message size that works at this ECC level is 2180, which, multiplied by 8, gives 17440, not "17948" as per the table. For 8 colors, we get 3271 * 8 = 26168 instead of 26925. (I'm looking at the Symbol net payload Pn (in bits) for Square Master and max Side-Version of 32).

I've tested it all on binary data and using only one (master) symbol.

**Comment by jabcode** [comment]
> The jabcode creator on the site I think should display the maximum amount of data that can be entered in the message box with the given configuration

Thank you for the suggestion. In case that the data only include numbers, the theoretical maximal payload can be reached. For mixed characters, it then depends on the input, as overhead for shifting between encoding modes has to be considered, with the exception of Byte mode.

**Comment by jabcode** [comment]
> In the meantime, I've used binary search to figure out the minimum message size at which the encoder refuses to encode it (or decoder fails to properly decode it). I've done this for all ECC levels (plus the "0" ECC level which I hacked in `encoder.h` to have wc = 3 and wr = 9 -- for some reason currently the "0" level is defined the same as level "3", contrary to Table 18 on page 41 of the paper).
> 
> Then I added two extra ECC levels (only checked this for 8 colours), -1 with wc = 3 and wr = 10; and -2 with wc = 3 and wr = 11 -- both of which still decoded fine. Having wr of 12 or more results in LDPC decoding failures, possibly due to the fact there's not enough bits to encode them in the metadata. Why are ECC choices limited so much..?
> 
> colours	ECC level	size
> 4	0	3394
> 4	1	3182
> 4	2	2909
> 4	3	2828
> 4	4	2545
> 4	5	2181
> 4	6	1696
> 4	7	1271
> 4	8	1016
> 4	9	846
> 4	10	725
> 8	-2	5554
> 8	-1	5346
> 8	0	5091
> 8	1	4773
> 8	2	4363
> 8	3	4246
> 8	4	3817
> 8	5	3272
> 8	6	2544
> 8	7	1907
> 8	8	1525
> 8	9	1270
> 8	10	1089
> Note that these results are not consistent with Table 1 on page 13 of the paper! This table mentions wc = 4, wr = 7, which corresponds to ECC level 5. For 4 colors, the maximum message size that works at this ECC level is 2180, which, multiplied by 8, gives 17440, not "17948" as per the table. For 8 colors, we get 3271 * 8 = 26168 instead of 26925. (I'm looking at the Symbol net payload Pn (in bits) for Square Master and max Side-Version of 32).
> 
> I've tested it all on binary data and using only one (master) symbol.

More ECC levels are defined in the new ISO version.
