### ISSUE TITLE
Rename master/slave to principal/auxiliary or primary/dependent

### ISSUE THREAD

**Issue by bluesmoon** [jabcode/jabcode#5]
New projects should not be using master/slave terminology. Using semantically more meaningful terms is better than terms that conjure up images of humans forced into servitude.

Suggested alternates:
* principal/auxiliary
* primary/dependent

**Comment by bsl** [comment]
I knew as soon as I glanced at the README that this kind of garbage issue or pull request would be here. The facts are, if you keep the terminology as-is, nobody is going to come to GitHub, see the word "slave", and conclude that slavery is OK. And if you change the terminology to something else, zero actual slaves will be emancipated and the conditions of zero slaves will be improved.

This type of request is not about actually accomplishing anything helpful in the world, it's just about complaining. If you give in to this kind of magical thinking, they may go away for a little while, but they'll be back again soon complaining about how sending a "kill" signal is too violent, that you shouldn't have a `die()` function, that you shouldn't have a "man" page, on and on and on. They'll find something.

**Comment by johncaseysmith** [comment]
Seconded. [Slippery-slope and strawman arguments against this have been made for years](https://github.com/django/django/pull/2692) and yet, the requests are always merged and the world continues to spin.

**Comment by themotu** [comment]
Principal and dependent are extremely offensive to me @bluesmoon

**Comment by tedivm** [comment]
I agree completely that the terminology should change, however I don't think this is the project where it should be changed. This is just an implementation of a technical spec, and that technical spec uses this terminology. Having one name in the technical spec and a different name in the library implementing it will cause confusion.

Since the technical specification is managed by the [BSI](https://www.bsi.bund.de/EN/Publications/TechnicalGuidelines/TR03137/BSITR03137.html) I think that is a more appropriate place to get the terminology changed.

**Comment by d-klein** [comment]
We'll think about it.
