### ISSUE TITLE
Truncated decoded data

### ISSUE THREAD

**Issue by murdak** [jabcode/jabcode#65]
Attached is sample image data (webp) file used to test encode and decode functionality.
[sample.zip](https://github.com/jabcode/jabcode/files/6791217/sample.zip)

Encoding sample image data would result:
![test_write_webp_v1](https://user-images.githubusercontent.com/15258808/125076520-9b786c00-e0f2-11eb-9f97-76e6ce0245b8.png)

Decoding the jabcode image would yield a truncated result - the webp tag of 4 bytes and two bytes of data.
Cutting off the rest of the data.

Tested with other webp image file as input data as well and yielded the same result of truncated data.
Tested with command line jabcodeReader and online tool: https://jabcode.org/scan would yield the same result.

**Comment by NathanJamesBlackerby** [comment]
...>jabcodeWriter.exe --input-file sample.webp --output test.png --symbol-number 1 --symbol-position 0 --symbol-version 32 32

...>jabcodeReader.exe test.png --output test.webp

...>fc sample.webp test.webp
Comparing files sample.webp and TEST.WEBP
FC: no differences encountered

This issue is not an issue. Note use --input-file for binary files and do not use --input for binary files. Close this issue.
Regarding the webp file type and trying to encode it with the --input option and just passing the file contents on the command line, webp file headers have file size at index 4 of size 4 bytes. Unless the file size has no 0x00 in those first 4 bytes strlen will report an input length of 4 to 7 bytes. For example sample.webp has a file size of 1730 bytes. The file size variable is for file size after index 7 so will be a value of file size - 8 which is 1722 which is 0x000006ba in hex which get written as 0xba060000 in the file which is why you got "the webp tag of 4 bytes and two bytes of data." Those bytes would be "RIFF" 0xBA 0x06.
